---
abstract: 'A hash table that supports multiple values per key.'
author:
  - 'Radek Slupik <rightfold@gmail.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Multihash
no_index:
  directory:
    - t
    - inc
requires:
  Set::Object: 1.34
  perl: 5.006
version: 0.01
